version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum install -y unzip jq --allowerasing
      - echo Downloading Trend Micro Cloud One Conformity Template Scanner...
      - curl -LO https://github.com/trendmicro/cloudone-template-scan/releases/latest/download/template_scan.zip
      - unzip template_scan.zip -d /usr/local/bin/
      - chmod +x /usr/local/bin/template_scan
      - template_scan version
  build:
    commands:
      - echo Running CloudFormation Template Scan...
      - template_scan scan --template-path template.yml --output results.json

artifacts:
  files:
    - results.json
